### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by momo-87** [til2to/javascript-capstone#27]
Great job, Congratulations!  
Your application looks very nice, kindly consider the following suggestion to improve the UX and the UI of your application:
- Population newly added comment once it is submitted;
- Consider adding a background color for the popup window for better font visibility;
- Add the close icon inside the popup window card;
- Consider increasing the font size of the footer text;
- Consider using the same size for the image box.

**Comment by supreeti** [comment]
Done required changes
